apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - image: bratusyung/go-server-app-k8s:latest
        imagePullPolicy: Always
        name: go-server
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      