apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server-service
  name: go-server-service
spec:
  ports:
  - name: http
    port: 31000        # Порт, на который будет доступен сервис
    targetPort: 8080   # Порт, на котором контейнер слушает
  selector:
    app: go-server     # Убедитесь, что метка соответствует метке в Deployment
