# I before writting this manifest i don't read insturction from github,
# and just go to read something on habr))
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: http
          imagePullPolicy: Always
          image: hashicorp/vault 
          ports:
          - containerPort: 8200
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]