apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - image: ifilyaninitmo/itdt-contained-frontend:master 
        imagePullPolicy: Always
        name: app-server
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: REACT_APP_USERNAME
          value: "CHEL"
        - name: REACT_APP_COMPANY_NAME
          value: "Mnogo_chelov"