apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-server-service
  name: app-server-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 31000        # Порт, на который будет доступен сервис
    targetPort: 3000   # Порт, на котором контейнер слушает
  selector:
    app: go-server     # Убедитесь, что метка соответствует метке в Deployment
