apiVersion: v1 # set api version
kind: Service # set type Service
metadata:
  labels:
    app: app-server-service # set labels
  name: app-server-service # set name of service
spec: # specification
  type: NodePort # set type of service - NodePort
  ports: # set ports info
  - name: http # name of port
    port: 31000        # internal port inside cluster
    targetPort: 3000   # service send trafic to this port
  selector:
    app: app-server
